version: "3"
name: "simple"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  pgsql:
    image: "postgres:13"
    container_name: simple_pgsql
    ports:
      - "${PG_PORT:-5432}:5432"
    environment:
      PGPASSWORD: "${PG_PASSWORD:-secret}"
      POSTGRES_DB: "${PG_DB_NAME:-default}"
      POSTGRES_USER: "${PG_USER?:err}"
      POSTGRES_PASSWORD: "${PG_PASSWORD:-secret}"
    volumes:
      - "simplepgsql:/var/lib/postgresql/data"
    networks:
      - simple
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${PG_DB_NAME:-default}",
          "-U",
          "${PG_USER}",
        ]
      retries: 3
      timeout: 5s
  mailhog:
    image: "mailhog/mailhog:latest"
    container_name: simple_mailhog
    ports:
      - "${MAILHOG_PORT:-1025}:1025"
      - "${MAILHOG_DASHBOARD_PORT:-8025}:8025"
    networks:
      - simple
networks:
  simple:
    driver: bridge
volumes:
  simplepgsql:
