export enum ITEM_CATEGORY {
	FOOD = "FOOD",
	DRINK = "DRINK",
	ELETRONICS = "ELETRONICS",
	OFFICE = "OFFICE",
	FASHION = "FASHION",
	BOOKS = "BOOKS",
	SPORTS = "SPORTS",
	BEAUTY = "BEAUTY",
	HEALTH = "HEALTH",
	TOYS = "TOYS",
	OTHERS = "OTHERS",
}
